<a href="https://colab.research.google.com/github/thatsmygirl/AI-project/blob/main/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import os
import cv2

In [5]:
DATADIR = 'drive/MyDrive/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train'
CATEGORIES = ['Apple___Apple_scab','Apple___Black_rot','Apple___Cedar_apple_rust']
IMG_SIZE=100

In [6]:
training_data=[]
def create_training_data():
    for category in CATEGORIES:
        path=os.path.join(DATADIR, category)
        class_num=CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array=cv2.imread(os.path.join(path,img))
                new_array=cv2.resize(img_array,(IMG_SIZE,IMG_SIZE))
                training_data.append([new_array,class_num])
            except Exception as e:
                pass
create_training_data()            

In [16]:
lenofimage = len(training_data)

X=[]
y=[]

for categories, label in training_data:
    X.append(categories)
    y.append(label)
X= np.array(X).reshape(lenofimage,-1)

X = X/255.0
y=np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

mlp = MLPClassifier(hidden_layer_sizes = (100, 80, 60, 40), learning_rate_init = 0.001,
                    batch_size = 512, solver = 'adam', verbose = True)
mlp.fit(X_train, y_train)

Iteration 1, loss = 2.20755248
Iteration 2, loss = 1.49476832
Iteration 3, loss = 1.14062804
Iteration 4, loss = 1.10199695
Iteration 5, loss = 1.14127628
Iteration 6, loss = 0.96385042
Iteration 7, loss = 1.24790120
Iteration 8, loss = 0.92250354
Iteration 9, loss = 0.86429028
Iteration 10, loss = 0.79940932
Iteration 11, loss = 0.83627261
Iteration 12, loss = 0.81330084
Iteration 13, loss = 0.78062694
Iteration 14, loss = 0.83953881
Iteration 15, loss = 1.65437437
Iteration 16, loss = 0.99910270
Iteration 17, loss = 1.19915139
Iteration 18, loss = 0.98347367
Iteration 19, loss = 1.03116828
Iteration 20, loss = 0.74732729
Iteration 21, loss = 0.72688687
Iteration 22, loss = 0.69211622
Iteration 23, loss = 0.65032962
Iteration 24, loss = 0.58286157
Iteration 25, loss = 0.98594587
Iteration 26, loss = 0.79340086
Iteration 27, loss = 0.81006767
Iteration 28, loss = 0.60929608
Iteration 29, loss = 0.72330539
Iteration 30, loss = 0.71553179
Iteration 31, loss = 0.59543184
Iteration 32, los

MLPClassifier(batch_size=512, hidden_layer_sizes=(100, 80, 60, 40),
              verbose=True)

In [17]:
y2 = mlp.predict(X_test)

In [18]:
conf = np.zeros((10, 10))
for i in range(len(y2)):
  conf[y2[i]][y_test[i]] += 1
print(conf)

correct = 0
for i in range(10):
  correct += conf[i][i]
accuracy = correct / len(y2)

print("Accuracy: ", accuracy * 100, "%")

[[273. 153.   4.   0.   0.   0.   0.   0.   0.   0.]
 [ 18. 198.   5.   0.   0.   0.   0.   0.   0.   0.]
 [121.  39. 342.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
Accuracy:  70.51170858629662 %
