<a href="https://colab.research.google.com/github/thatsmygirl/AI-project/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import numpy as np
import pandas as pd
import os
import cv2

In [13]:
DATADIR = 'drive/MyDrive/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train'
CATEGORIES = ['Apple___Apple_scab','Apple___Black_rot','Apple___Cedar_apple_rust']
IMG_SIZE=100

In [ ]:
training_data=[]
def create_training_data():
    for category in CATEGORIES:
        path=os.path.join(DATADIR, category)
        class_num=CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array=cv2.imread(os.path.join(path,img))
                new_array=cv2.resize(img_array,(IMG_SIZE,IMG_SIZE))
                training_data.append([new_array,class_num])
            except Exception as e:
                pass
create_training_data()            

In [ ]:
lenofimage = len(training_data)

X=[]
y=[]

for categories, label in training_data:
    X.append(categories)
    y.append(label)
X= np.array(X).reshape(lenofimage,-1)

X = X/255.0
y=np.array(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

svc = SVC(kernel='rbf',gamma=0.001)
svc.fit(X_train, y_train)

SVC(gamma=0.001)

In [ ]:
y2 = svc.predict(X_test)

In [ ]:
conf = np.zeros((10, 10))
for i in range(len(y2)):
  conf[y2[i]][y_test[i]] += 1
print(conf)

correct = 0
for i in range(10):
  correct += conf[i][i]
accuracy = correct / len(y2)

print("Accuracy: ", accuracy * 100, "%")

[[379.  20.   8.   0.   0.   0.   0.   0.   0.   0.]
 [ 27. 359.   5.   0.   0.   0.   0.   0.   0.   0.]
 [ 14.   0. 341.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
Accuracy:  93.58196010407632 %
